### PR TITLE
Closes #75 - Client memoize 

### LINKED ISSUE #75: Client doesn't recover from DNS refreshes
Right now `finagle-postgres` caches the DNS resolution forever when retrieving custom types from Postgres. That causes to the client to be forever dead even if the naming resolution succedes afterward, causing to Finagle stop complaining about `Name resolution failed` but still causing failures when trying to query anything.

```
[info] 18:38:46.899 DEBUG [finagle/netty4-4] connection-1 - Sent frontend message of type: com.twitter.finagle.postgres.messages.Sync$
[info] 18:38:46.899 DEBUG [finagle/netty4-4] state machine-1 - Received event com.twitter.finagle.postgres.messages.Sync$ in state com.twitter.finagle.postgres.connection.Connected$
[info] 18:38:46.899 DEBUG [finagle/netty4-4] state machine-1 - Transitioning to state com.twitter.finagle.postgres.connection.Syncing$ and emiting result
[info] 18:38:46.900 DEBUG [finagle/netty3-2] connection-1 - Received backend message of type: com.twitter.finagle.postgres.messages.ReadyForQuery
[info] 18:38:46.900 DEBUG [finagle/netty3-2] state machine-1 - Received event com.twitter.finagle.postgres.messages.ReadyForQuery in state com.twitter.finagle.postgres.connection.Syncing$
[info] 18:38:46.900 DEBUG [finagle/netty3-2] state machine-1 - Transitioning to state com.twitter.finagle.postgres.connection.Connected$ and emiting result
[info] 18:38:46.900 DEBUG [finagle/netty3-2] connection-1 - Emitting result com.twitter.finagle.postgres.messages.ReadyForQueryResponse$
[info] 18:38:46.901 WARN  [finagle/netty3-2] c.t.o.s.m.NoBrokersAvailableExceptionMapper - Name resolution failed with No hosts are available for db, Dtab.base=[], Dtab.local=[]. Aborting.
```

For now as a workaround we can create the client adding `withDefaultTypes()` and that will make it work. But only if all the types needed by the application are described in: https://github.com/finagle/finagle-postgres/blob/master/src/main/scala/com/twitter/finagle/postgres/PostgresClient.scala#L84

### PR DESCRIPTION
**Pull request by leonmaia**
This closes #75:
 - The strategy was to find a way to cache only successful evaluations of the `typeMap`. 
 - I chose to use the `Refresh` since it provides memoization for futures and doesn't cache failed ones.
 - `Refresh` provides us with an API to cache values that don't change often so we don't have to call the database every time and we also don't cache failed futures.
 - I also had to make sure that for when using the `prepareAndQuery` and the `prepareAndExecute` that the `typeMap` had been previously evaluated, that's why I added a `flatMap` on those two methods.

### CODE REVIEW

File: src/main/scala/com/twitter/finagle/postgres/PostgresClientImpl.scala [hunk 1]
```diff
@@ -80,20 +77,25 @@ class PostgresClientImpl(
...
+  private[postgres] val typeMap = Refresh.every(1.hour) {
+    types.map(Future(_)).getOrElse(retrieveTypeMap())
+  }
 
   // The OIDs to be used when sending parameters
-  private[postgres] val encodeOids = typeMap.map {
-    tm => tm.toIndexedSeq.map {
-      case (oid, PostgresClient.TypeSpecifier(receiveFn, typeName, elemOid)) => typeName -> oid
-    }.groupBy(_._1).mapValues(_.map(_._2).min)
+  private[postgres] val encodeOids = Refresh.every(1.hour) {
```
Comment (dangerousben) [inline src/main/scala/com/twitter/finagle/postgres/PostgresClientImpl.scala]: Do we need the extra `Refresh` here?  This should have the same effect:

``` scala
  private[postgres] val encodeOids = () => typeMap().map {
    tm => tm.toIndexedSeq.map {
      case (oid, PostgresClient.TypeSpecifier(receiveFn, typeName, elemOid)) => typeName -> oid
    }.groupBy(_._1).mapValues(_.map(_._2).min)
  }
```

File: src/main/scala/com/twitter/finagle/postgres/PostgresClientImpl.scala [hunk 2]
```diff
@@ -152,25 +154,32 @@ class PostgresClientImpl(
    * Issue a single, prepared SELECT query and wrap the response rows with the provided function.
    */
   override def prepareAndQuery[T](sql: String, params: Param[_]*)(f: Row => T): Future[Seq[T]] = {
-    for {
-      service <- factory()
-      statement = new PreparedStatementImpl("", sql, service)
-      result  <- statement.select(params: _*)(f)
-    } yield result
+    typeMap().flatMap { _ =>
```
Comment (dangerousben) [inline src/main/scala/com/twitter/finagle/postgres/PostgresClientImpl.scala:157]: Not sure these `flatMap`s are strictly necessary, they'll cause it to fail slightly sooner but it should fail anyway when `typeMap()` is accessed for real later down in the code.

**Review by dangerousben — COMMENTED** [review]
Couple of minor comments but in general looks good to me.

**Comment by leonmaia** [comment]
Thanks for the comments @dangerousben. I'll be addressing these days.

File: src/main/scala/com/twitter/finagle/postgres/PostgresClientImpl.scala (hunk 1 above)
Comment (leonmaia) [reply src/main/scala/com/twitter/finagle/postgres/PostgresClientImpl.scala]: Thanks @dangerousben, I removed the extra Refresh.

File: src/main/scala/com/twitter/finagle/postgres/PostgresClientImpl.scala (hunk 2 above)
Comment (leonmaia) [reply src/main/scala/com/twitter/finagle/postgres/PostgresClientImpl.scala:157]: I rather keep this, I know its not super necessary but I rather have it failing sooner.
